### ISSUE TITLE
Prices are gone the next day,

### ISSUE THREAD

**Issue by Tinus0172** [JaccoR/hass-entso-e#105]
Hello,

HA doesnt load the new prices for the next day and gives an error.

Logger: custom_components.entsoe.sensor
Source: custom_components/entsoe/sensor.py:128
Integration: ENTSO-e Transparency Platform ([documentation](https://github.com/JaccoR/hass-entso-e), [issues](https://github.com/JaccoR/hass-entso-e/issues))
First occurred: 12:38:03 (2 occurrences)
Last logged: 12:45:22
Unable to update entity due to data processing error: None and error: float division by zero

The graphs are empty and the entities dont give a new price.

Gr,

**Comment by Damazinho** [comment]
same here

**Comment by AOskam** [comment]
Same issue:

Logger: custom_components.entsoe.sensor
Source: custom_components/entsoe/sensor.py:128 
Integration: ENTSO-e Transparency Platform ([documentation](https://github.com/JaccoR/hass-entso-e), [issues](https://github.com/JaccoR/hass-entso-e/issues)) 
First occurred: 00:00:00 (78 occurrences) 
Last logged: 10:00:00

Unable to update entity due to data processing error: None and error: min() arg is an empty sequence


However other processing error

**Comment by Roeland54** [comment]
v0.4.0 is released this version contains fixes that solve a lot of warnings and known issues. This issue is probably also solved.
Please update to the latest version.
Closing this issue for now. If you still have issue please feel free to open a new issue.
