### ISSUE TITLE
async_update_data changes

### ISSUE THREAD

**Issue by SVH-Powel** [JaccoR/hass-entso-e#59]
I changed async_update_data to what is shown below. I am still testing!!
(I know I should create a pull request for this, but that is not possible at this time and the computer I have available)

I know this will fail when going from summer- to winter time as one day will have 25 hours (or 23 in the spring, when changing from winter- to summer time)

`

async def _async_update_data(self) -> dict:
        """Get the latest data from ENTSO-e"""
        self.logger.debug("Fetching ENTSO-e data")
        self.logger.debug(self.area)

        time_zone = dt.now().tzinfo
        # We request data for yesterday up until tomorrow.
        yesterday = pd.Timestamp.now(tz=str(time_zone)).replace(hour=0, minute=0, second=0) - pd.Timedelta(days = 1)
        tomorrow = yesterday + pd.Timedelta(hours = 71)

        data = await self.fetch_prices(yesterday, tomorrow)

        parsed_data = self.parse_hourprices(data)
        data_all = parsed_data[-49:].to_dict()
        if parsed_data.size > 48:
            data_today = parsed_data[-49:-24].to_dict()
            data_tomorrow = parsed_data[-24:].to_dict()
        else:
            data_today = parsed_data[-24:].to_dict()
            data_tomorrow = {}

        return {
            "data": data_all,
            "dataToday": data_today,
            "dataTomorrow": data_tomorrow,
        }
`

**Comment by sfstar** [comment]
See #53 and the explaination in the original question thread #41

**Comment by stigvi** [comment]
> See #53 and the explanation in the original question thread #41

Yes, of course :-) I saw a bug today that I wanted to fix. Today had yesterdays prices and tomorrow had todays prices. I suppose the intention is that both the today and tomorrow attribute list still change at midnight as they always did?

**Comment by stigvi** [comment]
I will test it until tomorrow afternoon and create a pull request when ready

**Comment by sfstar** [comment]
Yeah it's the same bug affecting #58 since they are computed by using `self.data["dataToday"]`
Since it currently is only updated at the release of the new prices they are only calculated for half a usefull day at a time.

Perhaps it's a good idea to redesign the behaviour of the attributes and the average etc entities (They use the same datasource set).
So that users can select whether they want the data to shift on:
-  price publish (current scenario)
- rotation (daily at midnight changing the attributes and entities)
- sliding (updated every hour by removing previous hours that are no longer used).

**Comment by sfstar** [comment]
For example I can think that people want to have everything reset when starting the new day.
While for automation and planning future hours to turn something on (like a consumption queue) it is better to have the values sliding (Because the queued thing needs to happen and previous pricing doesn't affect this need)
Publish behaviour would be slightly different compared to the current behaviour. It will be the same as the current "buggy" behaviour for the attributes while the average etc entities would include today and tommorow pricing from time of publish.

**Comment by sfstar** [comment]
If anybody can think of another behaviour type that somebody might want to have then please add to my list.
The behaviour selection itself could easily be implemented by a options setting with an default (==price publish) and all the other options.
Then the integration uses this option value in conditions for determining how to return attribute/entity data.

**Comment by sfstar** [comment]
@JaccoR could you (as the owner) say whether (if this change were to show up as an PR) you would be open to merging it? (Just checking so that no time is spend on something that will be still born 😳)

**Comment by JaccoR** [comment]
Nice idea, I am open for merging it if people are going to use it. I don't want to make the integration unnecessarily complicated though. I think the best way to handle this would be to add more attributes with all options. This way people who don't care and just want the sensors are not burdened with this "complicated" setting. I am not sure if this is possible though and if adding all those extra attributes causes any problems DB-wise. I currently have not a lot of time on my hands to work on this. Let me know if you are going to work on it and what your solution will be!

**Comment by sfstar** [comment]
#71 is the implementation of the rotation / sliding / publish mechanisms

**Comment by JaccoR** [comment]
merged!

**Comment by sfstar** [comment]
Thank you, could you release the change?
Also this issue can be closed now I guess :)
