### ISSUE TITLE
time of highest/lowest format not as intended?

### ISSUE THREAD

**Issue by Mariusthvdb** [JaccoR/hass-entso-e#64]
<img width="494" alt="Scherm­afbeelding 2022-11-04 om 14 48 22" src="https://user-images.githubusercontent.com/33354141/199988207-db94497b-3b6a-4f49-aa8a-663e5207f78b.png">

seems the same issue we had before

also, these are the only 2 mention 'energy' while electricity would bring it in accordance with the other entities?

> Time Of Highest Energy Price Today
> Time Of Lowest Energy Price Today

just another thought: since this integration is about electricity prices, and electricity only, wouldn't it be more efficient/less redundant to leave 'electricity' out of the name and entity_id completely? its what I do:

<img width="498" alt="Scherm­afbeelding 2022-11-04 om 14 52 21" src="https://user-images.githubusercontent.com/33354141/199989035-a6971c64-a9fd-4478-8dd0-c1b04aaa98a8.png">

and thanks for this new version, much better on the attributes! compliments for that.

**Comment by JaccoR** [comment]
tbh i have no idea what is causing this. No changes were made regarding this. Is this since daylight saving time switched?

**Comment by Mariusthvdb** [comment]
o I forgot to check that, sorry. could be indeed.

**Comment by JaccoR** [comment]
Yes that had to do with the name. Only when a name has been set the format would be wrong. But this time the format doesn't work for both cases: no name set and with a name set. So i think the issue is something else. The time string is in the right format and the sensor is set to device class timestamp. This is really bugging me and I can not figure out what the problem is.
