### ISSUE TITLE
When are prices updated when changing the price modifier template? 

### ISSUE THREAD

**Issue by woytekbode** [JaccoR/hass-entso-e#99]
I am trying to tweak the price modifier template but can't figure out when the changes take effect. Any change I make doesn't appear to result in different prices even after I reload/reinstall the integration and after I restart HA. Even with something simple as current_price + 1.0.

Anything I might be missing? Or ideas on how to force an update?

**Comment by JaccoR** [comment]
Am having the same issue. I have to look into this, did it not update after a while?

**Comment by woytekbode** [comment]
It did update after a while so I assume it updates with a new hourly price?

**Comment by evading** [comment]
I think the issue stems from the `async_added_to_hass` override in `EntsoeSensor` since that is called when the sensor is reloaded in hass at the end of reconfiguration. I have a [commit](https://github.com/JaccoR/hass-entso-e/commit/e5d623a8018253cd881021024c99aff5be477b3f) that just removes that override and it seems to solve this issue.

I'm not sure yet why the `EntsoSensorExtraStoredData` is needed when all the data is in the coordinator. Couldn't the sensor just get everything from there?

**Comment by MarcHagen** [comment]
> I think the issue stems from the `async_added_to_hass` override in `EntsoeSensor` since that is called when the sensor is reloaded in hass at the end of reconfiguration. I have a [commit](https://github.com/JaccoR/hass-entso-e/commit/e5d623a8018253cd881021024c99aff5be477b3f) that just removes that override and it seems to solve this issue.
> 
> I'm not sure yet why the `EntsoSensorExtraStoredData` is needed when all the data is in the coordinator. Couldn't the sensor just get everything from there?

This (still) works for me now, Thanks!

**Comment by scop** [comment]
@evading appears to work for me, too. Maybe file a PR here with that change?

**Comment by Roeland54** [comment]
v0.4.0 is released this version contains fixes that solve a lot of warnings and known issues. This issue is probably also solved.
Please update to the latest version.
Closing this issue for now. If you still have issue please feel free to open a new issue.
